haicais = ["O ano velho e o ano novo,\nComo se houvesse um bastão\nA trespassá-los.\n\n(Kyoshi)",
	"Primeiro dia do ano:\nMeu barraco,\nO mesmo de sempre.\n\n(Issa)",
	"Primeiro sonho do ano —\nSem contar a ninguém\nSorrio em silêncio.\n\n(Shô-u)",
	"Presentes de Ano Novo —\nAté o bebê de colo\nEstende as mãozinhas!\n\n(Issa)",
	"É anônimo o autor\nDeste esplêndido poema\nSobre a primavera.\n\n(Shiki)",
	"Dia de primavera —\nOs pardais no jardim\nTomam banho de areia.\n\n(Onitsura)",
	"A tranqüilidade\nDe andar sozinho,\nDivertir-se sozinho.\n\n(Shiki)",
	"Tranqüilidade —\nO monge da montanha\nEspia através da cerca.\n\n(Issa)",
	"Outro longo dia,\nE a primavera\nVai chegando ao fim!\n\n(Buson)",
	"Dias que se alongam —\nCada vez mais distantes\nOs tempos de outrora!\n\n(Buson)",
	"Vai-se a primavera!\nLágrimas no olho do peixe.\nChoram as aves.\n\n(Bashô)",
	"Morto de cansaço,\nA primavera chega ao fim\nEnquanto durmo.\n\n(Kitô)",
	"Farfalhando,\nA primavera se vai\nNo capim do prado.\n\n(Issa)",
	"Quando penso\nEm partir em viagem,\nO fim da primavera.\n\n(Kyoshi)",
	"As águas silentes\nE a névoa sobre o capim —\nEntardece agora.\n\n(Buson)",
	"Já é primavera —\nUma colina sem nome\nSob a névoa da manhã.\n\n(Bashô)",
	"Pelas vigas da ponte,\nOs raios de sol\nNa névoa da tarde.\n\n(Hokushi)",
	"Vento de primavera —\nDo outro lado do aterro,\nO mugido da vaca.\n\n(Raizan)",
	"Um gato sem dono\nDormindo sobre o telhado —\nChuva de primavera.\n\n(Taigi)",
	"A viva conversa\nDa capa e do guarda-chuva —\nChuva de primavera.\n\n(Buson)",
	"Chuva de primavera —\nTodas as coisas\nParecem mais bonitas.\n\n(Chiyo-jo)",
	"Chuva de primavera —\nUma criança\nEnsina o gato a dançar.\n\n(Issa)",
	"Ao derreter-se a neve,\nA aldeia se enche\nDe crianças!\n\n(Issa)",
	"O ar a tremular —\nA cada golpe da enxada\nO cheiro da terra.\n\n(Rankô)",
	"Mar de primavera —\nO dia todo,\nOndula, ondula...\n\n(Buson)",
	"Campo de primavera —\nPara onde vão, de onde vêm\nEstas pessoas?\n\n(Shiki)",
	"Uma pipa\nNo mesmo lugar\ndo céu de ontem!\n\n(Buson)",
	"Sobe\nDo barraco do mendigo\nUma linda pipa.\n\n(Issa)",
	"Tão mirrada,\nDe tanto arroz e cevada,\nA gata enamorada.\n\n(Bashô)",
	"Nem se lembra\nDo arroz grudado ao bigode —\nGato enamorado.\n\n(Taigi)",
	"O gato, ao acordar,\nCom um grande bocejo\nVai namorar.\n\n(Issa)",
	"Que coisa horrível!\nOs gatos enamorados\nDerrubaram o muro.\n\n(Shiki)",
	"Ah, o rouxinol!\nDe novo ele tenta\nE tenta de novo.\n\n(Chiyo-jo)",
	"A cada manhã,\nNo céu sobre o meu telhado,\nA mesma cotovia?\n\n(Jôsô)",
	"À cotovia,\nQue canta sem cessar,\nO dia inteiro não basta.\n\n(Bashô)",
	"Ah, quanta saudade\nDe meu pai e minha mãe\nNa voz do faisão.\n\n(Bashô)",
	"Entra pela cortina\nE à linda mulher se afeiçoa —\nUma andorinha.\n\n(Ransetsu)",
	"Acorda, acorda!\nVem ser minha amiga,\nBorboleta que dorme!\n\n(Bashô)",
	"Borboleta!\nO que sonhas, assim,\nmexendo suas asas?\n\n(Chiyo-jo)",
	"Sobre o sino,\nPousada dormita\nA borboleta.\n\n(Buson)",
	"Como se neste mundo\nNão tivesse mais esperanças,\nVai-se a borboleta!\n\n(Issa)",
	"Flutuando,\nAbandona-se ao vento\nUma borboleta.\n\n(Shiki)",
	"Para esta viagem\nA melhor companhia\nÉ uma borboleta!\n\n(Shiki)",
	"O velho lago ...\nO ruído do salto\nDa rã na água.\n\n(Bashô)",
	"No perfume das flores de ameixa,\nO sol de súbito surge —\nCaminho da montanha!\n\n(Bashô)",
	"Uma cai ...\nE duas caem a seguir —\nCamélias!\n\n(Shiki)",
	"Ao perder as flores\nCom o templo se confunde\nA cerejeira.\n\n(Buson)",
	"Da criança da aldeia\nA pele ainda branquinha —\nFlor de pessegueiro.\n\n(Chiyo-jo)",
	"A pereira em flor —\nNo antigo campo de guerra,\nA casa em ruínas.\n\n(Shiki)",
	"A lua da montanha\nGentilmente ilumina\nO ladrão de flores.\n\n(Issa)",
	"A criança às costas\nBrincando com meu cabelo —\nQue calor!\n\n(Sono-jo)",
	"Saio na varanda\nPara fugir da mulher e filhos.\nQue calor!\n\n(Buson)",
	"Apenas homens,\nE uma mulher entre eles.\nQue calor!\n\n(Shiki)",
	"Cúmulos-nimbos\nAtravessando os céus\nSobre o rio sem água.\n\n(Shiki)",
	"Recolhendo toda\nA chuva do mês de maio\nCorre o rio Mogami.\n\n(Bashô)",
	"Um aguaceiro —\nOs pardais da aldeia\nSe agarram ao capim.\n\n(Buson)",
	"Chuva de verão.\nOs pingos batem\nNas cabeças das carpas.\n\n(Shiki)",
	"Apenas\nOs bastões dos peregrinos —\nCampo de verão.\n\n(Ishû)",
	"O rio de verão —\nQue alegria atravessá-lo\nDe sandálias à mão.\n\n(Buson)",
	"Refresca um pouco\nPôr os pés na parede\n\n(Bashô)",
	"Ao fazer a sesta,\nA mão que segura o leque\nPára de se mexer...\n\n(Taigi)",
	"Que coisa linda,\nAgitando o leque branco,\nÉ o meu amor.\n\n(Buson)",
	"Oh, melões frescos,\nSe alguém aparecer,\nTransformem-se em rãs!\n\n(Issa)",
	"Mesmo em Quioto,\nSaudade de Quioto —\nO canto do cuco ...\n\n(Bashô)",
	"Se afasta a lanterna\nSumindo na escuridão —\nO canto do cuco.\n\n(Shiki)",
	"Olhe para o cuco\nQue só canta, canta e voa —\nQue vida ocupada!\n\n(Bashô)",
	"O canto do rouxinol\nE seu biquinho —\nAberto.\n\n(Buson)",
	"Salta uma truta —\nMovem-se as nuvens\nNo fundo do rio.\n\n(Onitsura)",
	"Na palma da mão,\nUm vagalume —\nSua luz é fria!\n\n(Shiki)",
	"Quietude —\nO canto das cigarras\nPenetra nas rochas.\n\n(Bashô)",
	"Nada indica\nQue ela vá morrer —\nCanta a cigarra.\n\n(Bashô)",
	"Veja o vento matinal\nSoprando os pêlos\nDa taturana!\n\n(Buson)",
	"Quando é que você veio\nPara junto de meus pés,\nOh, caramujo?\n\n(Issa)",
	"Caramujo,\nSuba sem pressa\nO Monte Fuji!\n\n(Issa)",
	"Ao matar a mosca\nA erva que tem flores\nTambem esmagada.\n\n(Issa)",
	"Em minha cabana\nÉ só assobiar\nQue vêm os mosquitos!\n\n(Issa)",
	"A mãe conta\nEnquanto dá de mamar\nAs picadas de pulga.\n\n(Issa)",
	"Também para as pulgas\nA noite deve ser longa\nE solitária.\n\n(Issa)",
	"Assim como a vela,\nMergulhada no silêncio,\nA peônia\n\n(Kyoroku)",
	"Quão glorioso,\nNas folhas verdes, folhas tenras,\nO brilho do sol!\n\n(Bashô)",
	"Entre a roça e a montanha,\nA chuvinha vai parando...\nA folhagem nova!\n\n(Buson)",
	"Sinos da tarde —\nNa passagem da montanha\nTremula o bambu novo.\n\n(Jôsô)",
	"A solidão\nDe uma estação de trem —\nFlores de lótus.\n\n(Shiki)",
	"Abriu-se a papoula\nE ao vento do mesmo dia\nEla veio ao chão.\n\n(Shiki)",
	"Tudo o que restou\nDos sonhos dos guerreiros —\nCapim de verão\n\n(Bashô)",
	"Em qualquer lugar\nOnde se deixem as coisas,\nAs sombras do outono.\n\n(Kyoshi)",
	"Ao mirar o espelho,\nNa primeira manhã de outono,\nO rosto do pai.\n\n(Kijô)",
	"Neste outono,\nComo estou ficando velho!\nPássaros nas nuvens.\n\n(Bashô)",
	"O pequeno córrego\nSe esconde sob o capim —\nO outono fenece.\n\n(Shirao)",
	"Hora do almoço.\nPela porta, com os raios de sol,\nAs sombras do outono.\n\n(Chora)",
	"Num galho seco,\nUm corvo pousado.\nTarde de outono.\n\n(Bashô)",
	"Por este caminho,\nNinguém mais passa —\nTarde de outono.\n\n(Bashô)",
	"Penso apenas\nEm meu pai e minha mãe —\nTarde de outono.\n\n(Buson)",
	"Lua cheia!\nPor mais que caminhe,\nO céu é de outro lugar.\n\n(Chiyo-jo)",
	"Lua cheia.\nMe dá, me dá!\nChora a criança.\n\n(Issa)",
	"Ah, lua de outono —\nAndando em volta do lago\nPassei toda a noite.\n\n(Bashô)",
	"Ah, lua cheia!\nNem mesmo um rosto bonito\nEntre os presentes...\n\n(Bashô)",
	"Ao deixar o portão\nDo templo zen,\nUma noite estrelada!\n\n(Shiki)",
	"Mar agitado —\nEstende-se até a ilha de Sado\nA Via-láctea.\n\n(Bashô)",
	"Solidão.\nApós a queima de fogos,\nUma estrela cadente.\n\n(Shiki)",
	"Apesar do sol\nArdendo sem compaixão,\nO vento de outono.\n\n(Bashô)",
	"Em solidão,\nComo minha comida —\nVento de outono.\n\n(Issa)",
	"No rabo do cavalo\nTambém há natureza búdica?\nVento de outono.\n\n(Shiki)",
	"Venerável\nÉ quem não se ilumina\nAo ver o relâmpago!\n\n(Bashô)",
	"Trovão —\nOntem a leste,\nHoje a oeste.\n\n(Kikaku)",
	"No orvalho branco\nEncontrarás o caminho\n\n(Issa)",
	"Algo faz barulho —\nCai sozinho, sem ajuda,\nO espantalho.\n\n(Bonchô)",
	"De espantalho\nPara espantalho,\nVoam os pardais.\n\n(Sazanami)",
	"Minha casa de sapê —\nSerá tempo de colheita\nNo mundo lá fora?\n\n(Bashô)",
	"Minha voz\nTorna-se vento —\nColeta de cogumelos.\n\n(Shiki)",
	"A moça rodeia\nO poeta que escreve versos —\nFestival das Estrelas.\n\n(Kyoshi)",
	"O velho cão,\nNa visita ao cemitério,\nSegue à frente.\n\n(Issa)",
	"Oh gansos selvagens!\nDesde que tempo\nTendes viajado?\n\n(Issa)",
	"Ah, esta casa —\nPica-paus vêm bicar\nSua madeira.\n\n(Bashô)",
	"A libélula,\nSem conseguir se agarrar\nA uma folha de capim.\n\n(Bashô)",
	"Sobre o curso d'água,\nPerseguindo sua sombra,\nDesliza a libélula.\n\n(Chiyo-jo)",
	"De noite minha sombra\nEmbebe-se na parede —\nO grilo cricrila\n\n(Ryôta)",
	"Noite na cabana —\nUm grilo na prateleira\nProcura por algo.\n\n(Issa)",
	"Que tocante!\nDebaixo da armadura\nSai um grilo.\n\n(Bashô)",
	"Libélulas!\nDá saudades da terra natal\nA cor deste muro.\n\n(Buson)",
	"A flor\nDa beira da estrada\nFoi comida pelo cavalo.\n\n(Bashô)",
	"Ao comer caqui\nOuve-se um sino tocar —\nTemplo Hôryûji.\n\n(Shiki)",
	"Sinos do anoitecer —\nO barulho de um caqui maduro\nCaindo no templo.\n\n(Shiki)",
	"O morro escurece\nE das folhas do bordo\nO escarlate rouba...\n\n(Buson)",
	"O salgueiro se desfolha.\nRestos de verduras\nDescendo o regato.\n\n(Shiki)",
	"As campânulas\nSe espalham pelo terreno —\nCasa abandonada.\n\n(Shiki)",
	"Início de inverno —\nMinha filha de dois anos\nEnsino a usar \"hashi\"\n\n(Gyôdai)",
	"O ano chega ao fim —\nCapa de chuva nas costas\nE sandálias nos pés.\n\n(Bashô)",
	"Estrelas, surgindo\nAqui e acolá —\nAh, o frio!\n\n(Taigi)",
	"No meio da noite,\nA voz das pessoas que passam —\nQue frio!\n\n(Yaha)",
	"A solidão\nApós matar uma aranha —\nNoite fria.\n\n(Shiki)",
	"Aconchegantes,\nOs raios do sol de inverno —\nMas que frio!\n\n(Onitsura)",
	"O som de um rato\nAndando sobre o prato —\nQue frio!\n\n(Buson)",
	"A lua crescente\nEstá arqueada —\nQue frio cortante!\n\n(Issa)",
	"Desolação de inverno —\nAo passar pela pequena aldeia,\nUm cão late.\n\n(Shiki)",
	"Nem mesmo uma pedra\nPara atirar no cachorro —\nLua de inverno.\n\n(Taigi)",
	"A lua fria —\nSobre o templo sem portão,\nO céu tão alto.\n\n(Buson)",
	"Sem ter companhia,\nE abandonada no campo,\nA lua de inverno.\n\n(Roseki)",
	"Mais fria que a neve,\nSobre os meus cabelos brancos,\nA lua de inverno.\n\n(Jôsô)",
	"Tormenta hibernal —\nO rosto do passante,\nInchado e dolorido.\n\n(Bashô)",
	"As estrelas no lago\nAparecem e desaparecem —\nChuva de inverno.\n\n(Sora)",
	"\"Viajante\",\nPoderia ser meu nome —\nPrimeira chuva de inverno.\n\n(Bashô)",
	"Primeira chuva de inverno —\nO macaco também quer\nUma capinha de palha.\n\n(Bashô)",
	"Sem guarda-chuva\nE sob a chuva de inverno —\nBem, bem!\n\n(Bashô)",
	"Chuva de inverno —\nPassando sobre o \"koto\"\nO ruído de um rato.\n\n(Buson)",
	"Primeira neve —\nEste velho penico\nÉ meu maior tesouro.\n\n(Issa)",
	"Manhã de neve.\nAté mesmo os cavalos\nFicamos olhando.\n\n(Bashô)",
	"Acenda o fogo.\nQue lhe mostro algo legal —\nUma grande bola de neve.\n\n(Bashô)",
	"Nada se move\nNo campo ou nas montanhas —\nManhã de neve.\n\n(Chiyo-jo)",
	"Apenas estando aqui,\nEstou aqui.\nE a neve cai.\n\n(Issa)",
	"Após urinar,\nUm buraco perfeito\nNa neve do portão!\n\n(Issa)",
	"Na tarde de neve\nPassa desaparecendo\nUm só guarda-chuva.\n\n(Yaha)",
	"\"Pouso para a noite!\"\nE joga sua espada ao chão —\nTormenta de neve\n\n(Buson)",
	"Sobre o campo seco,\nA voz que grita ao cavalo\nEm meio à tormenta.\n\n(Kyokusui)",
	"Doente de viagem,\nMeus sonhos vagueiam\npelo campo seco.\n\n(Bashô)",
	"Anoitece mais cedo —\nAs estrelas brilham\nSobre o campo seco.\n\n(Buson)",
	"Apenas um pássaro\nCompanheiro do caminho\nPelo campo seco.\n\n(Senna)",
	"Levando o cachorro\nO menino da vila\nPelo campo seco.\n\n(Shiki)",
	"O viajante\nChupa uma laranja\nPelo campo seco.\n\n(Shiki)",
	"O gelo é amargo\nPara o rato que no esgoto\nAplaca a sua sede.\n\n(Bashô)",
	"O Buda da roça —\nDa ponta do nariz\nUm filete de gelo.\n\n(Issa)",
	"Reclusão de inverno —\nAs montanhas de Yoshino\nNo fundo do coração.\n\n(Buson)",
	"Meu pai também\nViu estas montanhas —\nReclusão de inverno.\n\n(Issa)",
	"A chama da vela\nImóvel, arredondada —\nReclusão de inverno.\n\n(Yaha)",
	"Jardim no inverno —\nUm gato sem dono,\nDefecando.\n\n(Shiki)",
	"Eu e meu aquecedor —\nLá fora o Senhor do Feudo\nPassando ensopado.\n\n(Issa)",
	"O gato também\nVem aqui sentar conosco —\nFesta de fim de ano.\n\n(Issa)",
	"Anoitece no mar —\nOs gritos dos patos selvagens,\nVagamente brancos.\n\n(Bashô)",
	"Logo se esvaecem\nComo a lua na alvorada —\nMaçaricos da praia.\n\n(Chora)",
	"As folhas caindo\nNa roça em frente ao portão\nDivertem o gato.\n\n(Issa)",
	"Quietude —\nO barulho do pássaro\nPisando folhas secas.\n\n(Ryûshi)",
	"Varrer o chão\nE então parar de varrê-lo —\nEstas folhas secas.\n\n(Taigi)",
	"Dá para uma fogueira —\nO tanto de folhas secas\nTrazidas pelo vento.\n\n(Ryôkan)",
	"Cem anos de idade —\nA paisagem das folhas\nCaídas no jardim.\n\n(Bashô)",
	"Tão miseráveis,\nAs glicínias sem folhas\nDo velho templo.\n\n(Buson)",
	"Soprando o vento do oeste,\nAjuntam-se a leste\nAs folhas caídas.\n\n(Buson)",
	"Algumas pessoas.\nFolhas caem também\nAqui e ali.\n\n(Issa)",
	"O plantador de nabos,\nApontando com um nabo,\nEnsina o caminho.\n\n(Issa)",
	"As cebolinhas\nLavadas e tão brancas —\nQue frio!\n\n(Bashô)",
	"Saudosa de ti\ncaminho só pela rua.\nÉ noite de estio.\n\n(Fanny Dupré)",
	"Sobre a laje fria\ndiz adeus à primavera\numa rosa murcha.\n\n(Fanny Dupré)",
	"Ilhotas boiando.\nSob um céu vasto e sereno\neste mar tranqüilo.\n\n(Fanny Dupré)",
	"Tremendo de frio\nno asfalto negro da rua\na criança chora.\n\n(Fanny Dupré)",
	"Velho casarão.\nIluminam o interior\nraios de luar.\n\n(Fanny Dupré)",
	"Noite tenebrosa.\nPia a coruja agourenta\nno velho telhado.\n\n(Fanny Dupré)",
	"A pedra da rua.\nHumilham-te sem cessar.\nAh! os pés humanos...\n\n(Fanny Dupré)",
	"Noite fria, escura,\nno asfalto negro da rua\nlate o cão vadio.\n\n(Fanny Dupré)",
	"Laranjais em flor.\nAh! que perfume tenuíssimo...\nEsperei por ti...\n\n(Fanny Dupré)",
	"Bolha de sabão.\nBorboleta distraída...\nColisão no ar!\n\n(Fanny Dupré)",
	"Caem as flores murchas...\nNo quintal abandonado\num só mamoeiro.\n\n(Fanny Dupré)",
	"Rua São Luiz.\nNas nostálgicas sarjetas,\ndo ipê, flores roxas.\n\n(Fanny Dupré)",
	"Vendinha de bairro.\nRessona feliz gatinho\nno saco de estopa.\n\n(Fanny Dupré)",
	"Boêmio da noite\nno portão enferrujado.\nMorcego dormindo.\n\n(Fanny Dupré)",
	"Mosaico no muro.\nO gato ensaiando o pulo.\nAzuis borboletas.\n\n(Fanny Dupré)",
	"Crepita a fogueira...\nEntre nuvens mais estrelas.\nFogos de artifício.\n\n(Fanny Dupré)",
	"Em cima do túmulo,\ncai uma folha após outra.\nLágrimas também...\n\n(Goga)",
	"Primavera alegre\nOs namorados com walk-man\nPercorrem o parque.\n\n(Goga)",
	"Flores silvestres\npequeninas e sem brilho\nà espera de abelhas...\n\n(Goga)",
	"O ano fenecendo...\npreocupação nenhuma:\nsó penso em haiku!\n\n(Goga)",
	"As nuvens douradas\nFlutuam no pantanal\n- florada de ipê\n\n(Goga)",
	"Paineira em flor:\nCasa-grande abandonada,\nsem telha nem porta\n\n(Goga)",
	"Ah, mosca de inverno\n- questão de dia ou de hora -\nseu último instante?\n\n(Goga)",
	"Libélula voando\npára um instante e lança\nsua sombra no chão\n\n(Goga)",
	"Eco dos trovões:\nO aguaceiro, de repente,\nfaz subir o rio\n\n(Goga)",
	"À noite... sozinho...\nme deixam mais pensativo\nos cantos de insetos\n\n(Goga)",
	"Uma aldeia pobre,\nao pé da serra de inverno -\nmina antiga de ouro\n\n(Goga)",
	"Toque de buzina:\natravessa o rio seco\na boiada em ordem\n\n(Goga)",
	"O PENSAMENTO\n\nO ar. A folha. A fuga.\nNo lago, um círculo vago.\nNo rosto, uma ruga.\n\n(Guilherme de Almeida)",
	"HORA DE TER SAUDADE\n\nHouve aquele tempo...\n(E agora, que a chuva chora,\nouve aquele tempo!)\n\n(Guilherme de Almeida)",
	"INFÂNCIA\n\nUm gosto de amora\ncomida com sol. A vida\nchamava-se \"Agora\".\n\n(Guilherme de Almeida)",
	"CIGARRA\n\nDiamante. Vidraça.\nArisca, áspera asa risca\no ar. E brilha. E passa.\n\n(Guilherme de Almeida)",
	"CONSOLO\n\nA noite chorou\na bolha em que, sobre a folha,\no sol despertou.\n\n(Guilherme de Almeida)",
	"CHUVA DE PRIMAVERA\n\nVê como se atraem\nnos fios os pingos frios!\nE juntam-se. E caem.\n\n(Guilherme de Almeida)",
	"NOTURNO\n\nNa cidade, a lua:\na jóia branca que bóia\nna lama da rua.\n\n(Guilherme de Almeida)",
	"OS ANDAIMES\n\nNa gaiola cheia\n(pedreiros e carpinteiros)\no dia gorjeia.\n\n(Guilherme de Almeida)",
	"TRISTEZA\n\nPor que estás assim,\nvioleta? Que borboleta\nmorreu no jardim?\n\n(Guilherme de Almeida)",
	"PESCARIA\n\nCochilo. Na linha\neu ponho a isca de um sonho.\nPesco uma estrelinha.\n\n(Guilherme de Almeida)",
	"JANEIRO\n\nJasmineiro em flor.\nCiranda o luar na varanda.\nCheiro de calor.\n\n(Guilherme de Almeida)",
	"DE NOITE\n\nUma árvore nua\naponta o céu. Numa ponta\nbrota um fruto. A lua?\n\n(Guilherme de Almeida)",
	"FRIO\n\nNeblina? ou vidraça\nque o quente alento da gente,\nque olha a rua, embaça?\n\n(Guilherme de Almeida)",
	"FESTA MÓVEL\n\nNós dois? - Não me lembro.\nQuando era que a primavera\ncaía em setembro?\n\n(Guilherme de Almeida)",
	"ROMANCE\n\nE cruzam-se as linhas\nno fino tear do destino.\nTuas mãos nas minhas.\n\n(Guilherme de Almeida)",
	"Diante do vento\nTodo o caquizal se verga\nSaudando o poeta!\n\n(Francisco)",
	"Sob o céu nublado,\nPomar de caquis maduros\n-- lâmpadas acesas!\n\n(Francisco)",
	"Sacudindo os galhos,\nO vento que se alimenta\nDe caquis fresquinhos!\n\n(Teruko)",
	"Pomar de caquis:\nO bezerrinho prefere\nCardápio de capim!\n\n(Teruko)",
	"Sob o caquizeiro,\nUma erva desconhecida\nMostra suas frutinhas.\n\n(Edson)",
	"No fim do passeio:\nTirando picões da calça\nÀ sombra de uma árvore.\n\n(Edson)",
	"Uma folha rubra:\nDo ramo do caquizeiro\nesperando a queda!\n\n(Goga)",
	"Um bando de pássaros\nNo alto do céu: Deslizam\nNuvens outonais.\n\n(Goga)",
	"Dia da mentira:\nAquele ginkô sonhado\nSaiu como fato!\n\n(Goga)",
	"Ah! estas flores de ouro,\nque caem do ipê, são brinquedos\npr'as criancinhas pobres...\n\n(Jorge Fonseca Jr.)",
	"Para o sol que morre,\no algodoal estende, grato,\num lençol imenso...\n\n(Jorge Fonseca Jr.)",
	"Bem-te-vis cantando\nna festa de luz e cores!...\nFalta-me luz na alma...\n\n(Jorge Fonseca Jr.)",
	"Que tarde ventosa!...\nAh! nem tufão leva esta árvore\nque o cipó enlaçou!...\n\n(Jorge Fonseca Jr.)",
	"Bananal... calor...\nTropicalissimamente,\nvou chegando a Santos...\n\n(Jorge Fonseca Jr.)",
	"Este abacateiro\nacende, ante a luz do luar,\nsuas suaves lâmpadas...\n\n(Jorge Fonseca Jr.)",
	"Ah! o chimarrão quente!\nO frio forte dos pampas\nfoge um pouco assim!...\n\n(Jorge Fonseca Jr.)",
	"Estes girassois\nchamariam alto o sol,\nse tivessem voz!\n\n(Jorge Fonseca Jr.)",
	"O sabiá cantando,\nparece que esta saudade\nfoge-me um pouquinho...\n\n(Jorge Fonseca Jr.)",
	"Noite... praia... Nua,\ntesa, a palmeira se entrega\nao clarão do luar...\n\n(Jorge Fonseca Jr.)",
	"Nesta catedral,\nquando arde o sol, toda tarde,\nsangra este vitral...\n\n(Jorge Fonseca Jr.)",
	"Velame colhido,\nlá dorme, na noite enorme,\nnum porto esquecido...\n\n(Jorge Fonseca Jr.)",
	"Noite úmida e fria...\nNo chão da praça deserta,\ncai do ramo a flor...\n\n(Jorge Fonseca Jr.)",
	"Escurece rápido.\nInsistente, a corruíra\ncisca no quintal...\n\n(Jorge Fonseca Jr.)",
	"Frias, escorridas,\nas ramagens do chorão,\nno poço da noite...\n\n(Jorge Fonseca Jr.)",
	"A chuva parou.\nUm leve vapor, do chão,\nsobe e, ao sol, se irisa...\n\n(Jorge Fonseca Jr.)",
	"Ouro, prata e azul...\nE o vento fresco soprando\nna tarde que cai...\n\n(Jorge Fonseca Jr.)",
	"A folha caída,\npousada, seca, num galho,\ncomo um passarinho...\n\n(Jorge Fonseca Jr.)",
	"Ufa! que parece\nque a gente vai caminhando\ncom o sol às costas!...\n\n(Jorge Fonseca Jr.)",
	"Ao sol da manhã,\nas andorinhas, no fio,\nfazem a \"toilette\"...\n\n(Jorge Fonseca Jr.)",
	"Meiguice do sol\nno ninho do tico-tico\npiando no crepúsculo...\n\n(Jorge Fonseca Jr.)",
	"Fundo de quintal...\nSilêncio. No velho muro,\nuns cacos de sol...\n\n(Jorge Fonseca Jr.)",
	"Múrmura e ligeira,\npor sobre as flores da serra,\nvai a água entre as pedras...\n\n(Jorge Fonseca Jr.)",
	"Ervas de verão --\nRecolho com o laço\nOs bois um a um.\n\n(Nempuku Sato)",
	"O gado incomodado\nCom a presença do cão.\nFogueira no prado.\n\n(Nempuku Sato)",
	"Grande estiagem --\nTambém o gado\nComeça a definhar.\n\n(Nempuku Sato)",
	"Montado ao cavalo\nCom as esporas atadas\nE os pés descalços.\n\n(Nempuku Sato)",
	"Primeira montaria do ano --\nMeu filho corre atrás\nDo cavalo sem arreios.\n\n(Nempuku Sato)",
	"Trovão de primavera --\nChicote no cavalo\nMontado por dois.\n\n(Nempuku Sato)",
	"Café em flor...\nAo entrar pela porteira,\nChicote no cavalo!\n\n(Nempuku Sato)",
	"Caçada de lagartos.\nAté o cachorro manco\nTorna-se batedor.\n\n(Nempuku Sato)",
	"Após tocar\nUma vara de porcos,\nChega o trem dos imigrantes.\n\n(Nempuku Sato)",
	"Em volta do trem\nVendedores de doces --\nO campo seco.\n\n(Nempuku Sato)",
	"O ar tremulando\nJunto com os trilhos --\nDesembarque do trem.\n\n(Nempuku Sato)",
	"Cobertor às costas,\nDesligo o despertador\nE me levanto.\n\n(Nempuku Sato)",
	"De baixo das árvores\nAs pessoas saem dançando.\nChuvarada na roça.\n\n(Nempuku Sato)",
	"São todos meninos\nOs oleiros da olaria --\nVento de primavera.\n\n(Nempuku Sato)",
	"Palavras curtas\nEnvoltas no hálito branco.\nGênio complicado.\n\n(Nempuku Sato)",
	"Para o marido velho\nA jovem esposa\nQue dorme até tarde.\n\n(Nempuku Sato)",
	"O grandalhão\nMe encara\nPor trás da fogueira.\n\n(Nempuku Sato)",
	"Após tirar a água\nMe recosto sobre o poço --\nVai-se a primavera.\n\n(Nempuku Sato)",
	"Mudou a moça\nQue bombeia a água do poço --\nUma borboleta!\n\n(Nempuku Sato)",
	"Cachecol no pescoço --\nA barba de pioneiro\nCompete com a do padre.\n\n(Nempuku Sato)",
	"O aluno de Kyoshi entre ignorantes.\nPrimeiros insetos\nEm volta da lâmpada.\n\n(Nempuku Sato)",
	"Se houver fé\nPoucas palavras bastam.\nLume outonal.\n\n(Nempuku Sato)",
	"soprando esse bambu\nsó tiro\no que lhe deu o vento\n\n(Paulo Leminski)",
	"confira\ntudo que respira\nconspira\n\n(Paulo Leminski)",
	"duas folhas na sandália\no outono\ntambém quer andar\n\n(Paulo Leminski)",
	"a palmeira estremece\npalmas pra ela\nque ela merece\n\n(Paulo Leminski)",
	"passa e volta\na cada gole\numa revolta\n\n(Paulo Leminski)",
	"bateu na patente\nbatata\ntem gente\n\n(Paulo Leminski)",
	"verde a árvore caída\nvira amarelo\na última vez na vida\n\n(Paulo Leminski)",
	"nada me demove\nainda vou ser o pai\ndos irmãos karamazov\n\n(Paulo Leminski)",
	"na rua\n      sem resistir\nme chamam\ntorno a existir\n\n(Paulo Leminski)",
	"debruçado num buraco\nvendo o vazio\nir e vir\n\n(Paulo Leminski)",
	"casa com cachorro brabo\nmeu anjo da guarda\nabana o rabo\n\n(Paulo Leminski)",
	"cabelos que me caem\nem cada um\nmil anos de haikai\n\n(Paulo Leminski)",
	"as folhas tantas\no outono\nnem sabe a quantas\n\n(Paulo Leminski)",
	"a chuva vem de cima\ncorrem\ncomo se viesse atrás\n\n(Paulo Leminski)",
	"amei em cheio\nmeio amei-o\nmeio não amei-o\n\n(Paulo Leminski)",
	"pelos caminhos que ando\num dia vai ser\nsó não sei quando\n\n(Paulo Leminski)",
	"meiodia      três cores\neu disse vento\ne caíram todas as flores\n\n(Paulo Leminski)",
	"abrindo um antigo caderno\nfoi que eu descobri\nantigamente eu era eterno\n\n(Paulo Leminski)",
	"o mar o azul o sábado\nliguei pro céu\nmas dava sempre ocupado\n\n(Paulo Leminski)",
	"primeiro frio do ano\nfui feliz\nse não me engano\n\n(Paulo Leminski)",
	"ano novo\nanos buscando\num ânimo novo\n\n(Paulo Leminski)",
	"cortinas de seda\no vento entra\nsem pedir licença\n\n(Paulo Leminski)",
	"lua à vista\nbrilhavas assim\nsobre auschwitz?\n\n(Paulo Leminski)",
	"tudo dito,\nnada feito,\nfito e deito\n\n(Paulo Leminski)",
	"tarde de vento\naté as árvores\nquerem vir pra dentro\n\n(Paulo Leminski)",
	"tudo claro\nainda não era o dia\nera apenas o raio\n\n(Paulo Leminski)",
	"essa vida é uma viagem\npena eu estar\nsó de passagem\n\n(Paulo Leminski)",
	"longo o caminho\naté uma flor\nsó de espinho\n\n(Paulo Leminski)",
	"nadando num mar de gente\ndeixei lá atrás\nmeu passo à frente\n\n(Paulo Leminski)",
	"noite alta   lua baixa\npergunte ao sapo\no que ele coaxa\n\n(Paulo Leminski)",
	"nu como um grego\nouço um músico negro\ne me desagrego\n\n(Paulo Leminski)",
	"a noite - enorme\ntudo dorme\nmenos teu nome\n\n(Paulo Leminski)",
	"tatami-o ou deite-o\n\nde colchão em colchão\nchego à conclusão\nmeu lar é no chão\n\n(Paulo Leminski)",
	"madrugada     bar aberto\ndeve haver algum engano\npor perto\n\n(Paulo Leminski)",
	"acabou a farra\nformigas mascam\nrestos da cigarra\n\n(Paulo Leminski)",
	"minha alma breve breve\no elemento mais leve\nda tabela de mendeleiev\n\n(Paulo Leminski)",
	"essa idéia\nninguém me tira\nmatéria é mentira\n\n(Paulo Leminski)",
	"jardim da minha amiga\ntodo mundo feliz\naté a formiga\n\n(Paulo Leminski)"]
